name: Build Optimized Mobile Kernel
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache ccache
        uses: actions/cache@v4
        with:
          path: |
            ~/.ccache
          key: ${{ runner.os }}-ccache-${{ hashFiles('Makefile') }}
          restore-keys: |
            ${{ runner.os }}-ccache-

      - name: Setup Build Environment
        run: |
          echo "=== Installing Dependencies ==="
          sudo apt-get update
          sudo apt-get install -y \
            gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi \
            clang-16 lld-16 llvm-16 \
            git make bc bison openssl \
            libssl-dev flex zip curl \
            ccache automake lzop python3 \
            binutils-aarch64-linux-gnu

      - name: Setup LLVM Toolchain
        run: |
          echo "=== Setting up LLVM Toolchain ==="
          sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-16 100
          sudo update-alternatives --install /usr/bin/ld.lld ld.lld /usr/bin/ld.lld-16 100
          sudo update-alternatives --install /usr/bin/llvm-ar llvm-ar /usr/bin/llvm-ar-16 100
          sudo update-alternatives --install /usr/bin/llvm-nm llvm-nm /usr/bin/llvm-nm-16 100
          sudo update-alternatives --install /usr/bin/llvm-objcopy llvm-objcopy /usr/bin/llvm-objcopy-16 100
          sudo update-alternatives --install /usr/bin/llvm-objdump llvm-objdump /usr/bin/llvm-objdump-16 100
          sudo update-alternatives --install /usr/bin/llvm-strip llvm-strip /usr/bin/llvm-strip-16 100

          echo "=== Checking Toolchain Versions ==="
          clang --version
          ld.lld --version
          llvm-ar --version

      - name: Setup Kernel Configuration
        run: |
          echo "=== Setting up Kernel Configuration ==="
          export ARCH=arm64
          export SUBARCH=arm64
          export CROSS_COMPILE=aarch64-linux-gnu-
          export CROSS_COMPILE_ARM32=arm-linux-gnueabi-
          export CC=clang
          export CLANG_TRIPLE=aarch64-linux-gnu-
          export AR=llvm-ar
          export NM=llvm-nm
          export OBJCOPY=llvm-objcopy
          export OBJDUMP=llvm-objdump
          export STRIP=llvm-strip
          export LD=ld.lld
          
          mkdir -p out
          mkdir -p arch/arm64/boot/dts
          
          # 使用设备默认配置
          make O=out ARCH=arm64 clover_defconfig
          
          # 优化配置
          ./scripts/config --file out/.config \
            -e LTO \
            -e LTO_CLANG \
            -e LLVM \
            -e LLVM_POLLY \
            -e CFI \
            -e CFI_PERMISSIVE \
            -e CFI_CLANG \
            -e THINLTO \
            -e ARM64_CRYPTO \
            -e CRYPTO_AES_ARM64_CE_CCM \
            -e CRYPTO_AES_ARM64_CE_BLK \
            -e CRYPTO_SHA1_ARM64_CE \
            -e CRYPTO_SHA2_ARM64_CE \
            -e CRYPTO_SHA512_ARM64_CE \
            -e CRYPTO_SHA3_ARM64 \
            -e CRYPTO_GHASH_ARM64_CE \
            -e KPROBES \
            -e OPTPROBES \
            -e KPROBES_ON_FTRACE \
            -e HAVE_KPROBES \
            -e HAVE_KPROBES_ON_FTRACE \
            -e HAVE_OPTPROBES \
            -e PREEMPT \
            -d DEBUG_INFO \
            -d DEBUG_INFO_DWARF4 \
            -d DEBUG_INFO_DWARF5 \
            -d SLUB_DEBUG \
            -d SLUB_DEBUG_ON \
            -d STACKTRACE \
            -d DYNAMIC_DEBUG
          
          # 更新配置
          make O=out ARCH=arm64 olddefconfig
          
          echo "=== Kernel Configuration Summary ==="
          grep -E "CONFIG_(LTO|LLVM|CFI|CRYPTO|PREEMPT|DEBUG).*=" out/.config

      - name: Build Kernel
        run: |
          echo "=== Building Kernel ==="
          export ARCH=arm64
          export SUBARCH=arm64
          export CROSS_COMPILE=aarch64-linux-gnu-
          export CROSS_COMPILE_ARM32=arm-linux-gnueabi-
          export CC=clang
          export CLANG_TRIPLE=aarch64-linux-gnu-
          export AR=llvm-ar
          export NM=llvm-nm
          export OBJCOPY=llvm-objcopy
          export OBJDUMP=llvm-objdump
          export STRIP=llvm-strip
          export LD=ld.lld
          export LLVM=1
          export LLVM_IAS=1
          export CCACHE_DIR=~/.ccache
          
          # 优化参数
          KBUILD_CFLAGS="-O3 -mtune=native -march=native"
          KBUILD_CFLAGS+=" -fdata-sections -ffunction-sections"
          KBUILD_CFLAGS+=" -fno-common -fno-strict-aliasing"
          KBUILD_CFLAGS+=" -pipe -ffast-math"
          KBUILD_CFLAGS+=" -flto=thin"
          export KBUILD_CFLAGS
          
          echo "=== Starting Optimized Kernel Build ==="
          make O=out \
            ARCH=arm64 \
            CC=clang \
            CLANG_TRIPLE=aarch64-linux-gnu- \
            LLVM=1 \
            LLVM_IAS=1 \
            AR=llvm-ar \
            NM=llvm-nm \
            LD=ld.lld \
            STRIP=llvm-strip \
            OBJCOPY=llvm-objcopy \
            OBJDUMP=llvm-objdump \
            KBUILD_CFLAGS="$KBUILD_CFLAGS" \
            -j$(nproc --all) 2>&1 | tee build.log
          
          if [ -f out/arch/arm64/boot/Image.gz-dtb ]; then
            echo "✅ Kernel compiled successfully!"
            ls -lh out/arch/arm64/boot/Image.gz-dtb
          else
            echo "❌ Kernel compilation failed!"
            echo "=== Build Log Tail ==="
            tail -n 100 build.log
            exit 1
          fi

      - name: Post Build Analysis
        if: success()
        run: |
          echo "=== Kernel Size Analysis ==="
          ls -lh out/arch/arm64/boot/Image*
          
          echo "=== Checking LTO Status ==="
          nm out/vmlinux | grep -c "LLVM" || true
          
          echo "=== Security Features ==="
          readelf -S out/vmlinux | grep -i "gnu"

      - name: Create Release Package
        if: success()
        run: |
          echo "=== Creating Release Package ==="
          mkdir -p release
          cp out/arch/arm64/boot/Image.gz-dtb release/
          cd release
          zip -r9 ../kernel-release.zip *

      - name: Upload Build Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: kernel-build-${{ github.run_id }}
          path: |
            kernel-release.zip
            build.log
            out/.config
          retention-days: 7

      - name: Cleanup
        if: always()
        run: |
          echo "=== Cleaning up ==="
          make O=out clean
          make O=out mrproper
          ccache -s
          echo "=== Final Disk Space ==="
          df -h
