name: Setup Submodules
on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Submodules
        run: |
          # 初始化子模块
          git submodule init
          
          # 添加 KernelSU 子模块
          git submodule add https://github.com/rifsxd/KernelSU-Next.git KernelSU
          
          # 添加 SUSFS 子模块（指定分支）
          git submodule add -b kernel-4.19 https://gitlab.com/simonpunk/susfs4ksu.git SUSFS
          
          # 更新子模块
          git submodule update --recursive --remote
          
          # 显示状态
          git submodule status

      - name: Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Initialize submodules"
          git push
